export const ManageCaseSearchForm = ({ defaultValue = {}, status }) => {
  return [
    {
      key: "1",
      span: 6,
      disabled: false,
      name: "request_no",
      label: "Request No.",
      type: "INPUT",
      value: "",
      defaultValue: "",
    },
    {
      key: "2",
      span: 6,
      disabled: false,
      name: "status",
      label: "สถานะ",
      type: "SELECT",
      value: "",
      options: defaultValue.optionStatus,
      defaultValue: "PENDING",
    },
    {
      key: "4",
      span: 6,
      disabled: false,
      name: "requesters_name",
      label: "Request Name",
      type: "INPUT",
      value: "",
      defaultValue: "",
    },
    {
      key: "5",
      span: 6,
      disabled: false,
      name: "department_sup",
      label: "Department supervisor",
      type: "INPUT",
      value: "",
      defaultValue: "",
    },
    {
      key: "6",
      span: 6,
      disabled: false,
      name: "urgency",
      label: "ความเร่งด่วน",
      type: "SELECT",
      value: "",
      options: defaultValue.optionUrgency,
      defaultValue: defaultValue.urgency || "",
    },

    {
      key: "8",
      span: 6,
      disabled: false,
      name: "type_desired",
      label: "ประเภทอุปกรณ์",
      type: "SELECT",
      value: "",
      options: defaultValue.optionType,
      defaultValue: defaultValue.type_desired || "",
    },
    {
      key: "9",
      span: 6,
      disabled: false,
      name: "accessory_hw",
      label: "อุปกรณ์-HW",
      type: "SELECT",
      value: "",
      options: defaultValue.optionHw,
      defaultValue: defaultValue.accessory_hw || "",
    },
    {
      key: "10",
      span: 6,
      disabled: false,
      name: "duedate",
      label: "Duedate",
      type: "RANGE_PICKER",
      value: "",
      defaultValue: "",
      rules: {
        required: false,
      },
      format: "YYYY-MM-DD",
      allowClear: true,
    },
    {
      key: "11",
      span: 6,
      disabled: false,
      name: "it_comment",
      label: "IT (comment)",
      type: "INPUT",
      value: "",
      defaultValue: "",
    },
    {
      key: "11",
      span: 6,
      disabled: false,
      name: "it_followup",
      label: "IT FollowUp",
      type: "SELECT",
      value: "",
      options: defaultValue.optionIt,
      defaultValue: defaultValue.it_followup || "",
    },
    {
      key: "12",
      span: 6,
      disabled: false,
      name: "pr_ep",
      label: "PR/EP",
      type: "INPUT",
      value: "",
      defaultValue: "",
    },
  ];
};
